logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://bb-db.mysql.database.azure.com:3306/cruise_groups?allowPublic.KeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        show_sql: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true


hostName: https://bb-spring-app-grouman.azuremicroservices.io

mail:
  host: ${MAIL_HOST:localhost}
  port: ${MAIL_PORT:1025}
  username: ${MAIL_USER:admin}
  password: ${MAIL_PASS:}


