logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/cruisegroups?useSSL=false&createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        show_sql: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

hostName: http://localhost:8080

app:
  default:
    password: ${topsecret}

mail:
  host: localhost
  port: 1025
  username: "admin"
  password: ""


