version: '3.4'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin', '--default-authentication-plugin=mysql_native_password' ]
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_DATABASE=cruisegroups
      - MYSQL_USER=cg
      - MYSQL_PASSWORD=1234

  mailhog:
    image: mailhog/mailhog:latest
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui%
    environment:
      - MAIL_USER=admin
      - MAIL_PASS:=

  cgm-0.8.0:
    image: boboev/cgm:v0.8
    depends_on: [db]
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=cg
      - MYSQL_PASSWORD=1234
      - HOSTNAME=http://localhost:8080
